# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fuente_de_Financiacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipoFinanciacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_De_Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_IES', models.CharField(max_length=50)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('fecha_inicio_grupo', models.DateField()),
                ('fecha_vigencia_grupo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('areaConocimiento', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Linea_Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inscritos', models.CharField(max_length=100)),
                ('finalizados', models.CharField(max_length=100)),
                ('aprobaron', models.CharField(max_length=100)),
                ('cancelaron', models.CharField(max_length=100)),
                ('perdieron', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MacroProyecto',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maximo_Nivel_Educativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nucleo_Basico_Conocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('nbc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_de_Investigacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('ano_obtencion_producto', models.CharField(max_length=100)),
                ('mes_obtencion_producto', models.CharField(max_length=100)),
                ('costo_producto', models.FloatField()),
                ('codigo_IES', models.CharField(max_length=100)),
                ('nombre_IES', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_IES', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('ano', models.CharField(blank=True, max_length=50, null=True)),
                ('semestre', models.CharField(blank=True, max_length=50, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('objetivo_socioeconomico', models.TextField(blank=True, null=True)),
                ('objetivo_proyecto', models.TextField()),
                ('resumen_proyecto', models.TextField(blank=True, null=True)),
                ('resultados_esperados', models.TextField(blank=True, null=True)),
                ('sede', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_materia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_materia', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo_materia', models.CharField(blank=True, max_length=50, null=True)),
                ('horas_asignadas_docente', models.IntegerField(blank=True, null=True)),
                ('gasto_total', models.FloatField(blank=True, null=True)),
                ('tipo_De_gasto', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_semana', models.FloatField(blank=True, null=True)),
                ('perfiles', models.CharField(max_length=100)),
                ('realizo_Sustentacion_publica', models.CharField(blank=True, max_length=50, null=True)),
                ('otras_Entidades_Participantes', models.CharField(blank=True, max_length=50, null=True)),
                ('asociado_al_area_de_conocimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('finalizado', models.CharField(blank=True, max_length=50, null=True)),
                ('paz_y_salvo', models.CharField(blank=True, max_length=50, null=True)),
                ('modalidad_de_seminario', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=100)),
                ('cupoMax', models.CharField(blank=True, max_length=50, null=True)),
                ('cupoMin', models.CharField(blank=True, max_length=50, null=True)),
                ('Fuente_de_financiacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Fuente_de_Financiacion')),
                ('NBC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Nucleo_Basico_Conocimiento')),
                ('directorDeProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Empresa')),
                ('idGrupo_investigacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Grupo_De_Investigacion')),
                ('id_lineas_investigacion_asociadas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Linea_Investigacion')),
                ('maximo_nivel_educativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Maximo_Nivel_Educativo')),
                ('nombreMacroProyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.MacroProyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Red_de_Coperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('codigo_IES', models.CharField(max_length=100)),
                ('nombre_IES', models.CharField(max_length=100)),
                ('fecha_Creacion_Red', models.DateField()),
                ('sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sublinea',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sustentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('salon', models.CharField(max_length=100)),
                ('nombreJurados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Jurado')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_Participacion_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Proyecto',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='red_investigacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Red_de_Coperacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='sublinea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Sublinea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_participacion_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.tipo_Participacion_Proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Tipo_Proyecto'),
        ),
        migrations.AddField(
            model_name='producto_de_investigacion',
            name='idProyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proyecto'),
        ),
    ]
