# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Sustentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Sustentacion'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='jurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Jurado'),
        ),
    ]
