# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estudiante', '0001_initial'),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=100)),
                ('fecha_publicacion', models.CharField(max_length=100)),
                ('enlaceImagen', models.CharField(max_length=500)),
                ('enlaaceVideo', models.CharField(max_length=500)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(max_length=100)),
                ('mail_institucional', models.CharField(max_length=100)),
                ('nro_Proyectos_a_Cargo', models.IntegerField(blank=True, null=True)),
                ('rol', models.CharField(max_length=100)),
                ('programa_Consecutivo', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_Programa', models.CharField(blank=True, max_length=100, null=True)),
                ('investigacion', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_Investigacion_Trabajo_grado', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('rol_Segun_Colciencias', models.CharField(blank=True, max_length=100, null=True)),
                ('nombreMateriaProgramaEstudiante', models.CharField(blank=True, max_length=100, null=True)),
                ('codigoMateriaProgramaEstudiante', models.CharField(blank=True, max_length=100, null=True)),
                ('estadoInscripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fkCiclo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Ciclo')),
                ('fkFacultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Facultad')),
                ('fkPrograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.Programa')),
                ('fkProyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrador.Proyecto')),
                ('fk_authUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
