# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 18:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_Limite', models.DateField()),
                ('corte', models.CharField(max_length=100)),
                ('nota', models.CharField(max_length=100)),
                ('porcentaje', models.CharField(max_length=100)),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('documentoAdjunto', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=100)),
                ('idDirector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad_Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('desarrollo', models.CharField(blank=True, max_length=100, null=True)),
                ('adjunto', models.CharField(blank=True, max_length=100, null=True)),
                ('UsuarioEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorDeProyecto.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('porcentaje', models.IntegerField(blank=True, null=True)),
                ('nota', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='actividad_estudiante',
            name='nombreCorte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorDeProyecto.Corte'),
        ),
    ]
