# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorDeProyecto', '0002_auto_20161023_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='documentoAdjunto',
            field=models.FileField(upload_to='Documentos/documentsDirector/'),
        ),
        migrations.AlterField(
            model_name='actividad_estudiante',
            name='adjunto',
            field=models.FileField(null=True, upload_to='Documentos/documentsEstudiante/'),
        ),
    ]
